<#
.SYNOPSIS
    Scaffold AGENTS.md and a worker prompt into a target repo so the local
    AI worker can run against it without manual setup.

.DESCRIPTION
    Idempotent: existing files are left alone. The user's repo gets:

      AGENTS.md                          (instructions for any agent)
      .ai-agent-tools/web-worker.md      (worker prompt the runner reads)

    The script auto-detects the repo's stack (npm, Python, mixed, unknown) and
    annotates the dropped files with the validation commands that match.

    No commits, no pushes. Files are dropped untracked; the user reviews them
    and decides whether to commit.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$RepoPath,

    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
if (Get-Variable PSNativeCommandUseErrorActionPreference -ErrorAction SilentlyContinue) {
    $PSNativeCommandUseErrorActionPreference = $false
}

$Root = "C:\ai-agent-tools"
$AgentsTemplate = Join-Path $Root "configs\AGENTS.web.template.md"
$WorkerPromptSource = Join-Path $Root "prompts\web-worker-prompt.md"

if (-not (Test-Path -LiteralPath $RepoPath)) { throw "RepoPath does not exist: $RepoPath" }
if (-not (Test-Path -LiteralPath (Join-Path $RepoPath ".git"))) { throw "Not a git repository: $RepoPath" }

# --- Stack detection -----------------------------------------------------
function Get-Stacks {
    param([string]$Path)
    $stacks = New-Object System.Collections.Generic.List[string]
    if (Test-Path (Join-Path $Path "package.json"))          { [void]$stacks.Add("npm") }
    if (Test-Path (Join-Path $Path "pyproject.toml"))        { [void]$stacks.Add("python") }
    elseif (Test-Path (Join-Path $Path "requirements.txt"))  { [void]$stacks.Add("python") }
    if (Test-Path (Join-Path $Path "Cargo.toml"))            { [void]$stacks.Add("rust") }
    if (Test-Path (Join-Path $Path "go.mod"))                { [void]$stacks.Add("go") }
    if (Test-Path (Join-Path $Path "pom.xml"))               { [void]$stacks.Add("java") }
    if (Test-Path (Join-Path $Path "build.gradle"))          { [void]$stacks.Add("java") }
    if ($stacks.Count -eq 0)                                 { [void]$stacks.Add("unknown") }
    return $stacks
}

function Get-ValidationLines {
    param([string[]]$Stacks)
    $lines = New-Object System.Collections.Generic.List[string]
    if ($Stacks -contains "npm") {
        [void]$lines.Add("- npm run lint")
        [void]$lines.Add("- npm run typecheck")
        [void]$lines.Add("- npm run build")
        [void]$lines.Add("- npm run test")
    }
    if ($Stacks -contains "python") {
        [void]$lines.Add("- ruff check . (or `python -m ruff check .`)")
        [void]$lines.Add("- pytest -q")
    }
    if ($Stacks -contains "rust") {
        [void]$lines.Add("- cargo check")
        [void]$lines.Add("- cargo test")
    }
    if ($Stacks -contains "go") {
        [void]$lines.Add("- go build ./...")
        [void]$lines.Add("- go test ./...")
    }
    if ($Stacks -contains "java") {
        [void]$lines.Add("- ./gradlew build (or `mvn verify`)")
    }
    if ($lines.Count -eq 0) {
        [void]$lines.Add("- (no validation commands detected; the agent should ask before running anything)")
    }
    return $lines
}

# --- AGENTS.md -----------------------------------------------------------
function Write-AgentsFile {
    param(
        [string]$DestPath,
        [string[]]$Stacks
    )

    $stackLine = ($Stacks -join ", ")
    $validation = (Get-ValidationLines -Stacks $Stacks) -join [Environment]::NewLine

    $template = if (Test-Path -LiteralPath $AgentsTemplate) {
        (Get-Content -Raw -Path $AgentsTemplate).TrimEnd()
    }
    else {
        @"
# AI Agent Instructions

## Rules

- Make small, reviewable changes.
- Prefer fixing validation errors before adding new features.
- Do not modify secrets, .env files, tokens, auth config, payment config, production deployment config, or database migrations.
- Do not touch node_modules, dist, build, .next, coverage, .git, cache folders, or generated files.
- Do not push to main.
- Stop after one small task.
"@.TrimEnd()
    }

    $banner = @"
<!--
  Auto-generated by C:\ai-agent-tools\scripts\init-repo-agents.ps1.
  Detected stack: $stackLine
  Re-run with -Force to refresh.
-->
"@

    $stackSection = @"

## Detected Stack

$stackLine

## Validation Commands (preferred)

$validation
"@

    Set-Content -Path $DestPath -Encoding UTF8 -Value ($banner + [Environment]::NewLine + $template + [Environment]::NewLine + $stackSection)
}

# --- worker prompt -------------------------------------------------------
function Write-WorkerPrompt {
    param([string]$DestPath)

    $body = if (Test-Path -LiteralPath $WorkerPromptSource) {
        (Get-Content -Raw -Path $WorkerPromptSource).TrimEnd()
    }
    else {
        "You are a small local AI worker. Make one small safe edit. Do not push or commit."
    }

    $banner = @"
<!--
  Worker prompt mirrored by C:\ai-agent-tools\scripts\init-repo-agents.ps1
  from C:\ai-agent-tools\prompts\web-worker-prompt.md.
-->
"@
    Set-Content -Path $DestPath -Encoding UTF8 -Value ($banner + [Environment]::NewLine + $body)
}

# --- main ---------------------------------------------------------------
$stacks = Get-Stacks -Path $RepoPath
Write-Host "[init-repo-agents] Detected stack: $($stacks -join ', ')"

$wrote = New-Object System.Collections.Generic.List[string]
$skipped = New-Object System.Collections.Generic.List[string]

$agentsPath = Join-Path $RepoPath "AGENTS.md"
if ((Test-Path -LiteralPath $agentsPath) -and -not $Force) {
    [void]$skipped.Add("AGENTS.md (already present; pass -Force to overwrite)")
}
else {
    Write-AgentsFile -DestPath $agentsPath -Stacks $stacks
    [void]$wrote.Add("AGENTS.md")
}

$promptDir = Join-Path $RepoPath ".ai-agent-tools"
New-Item -ItemType Directory -Path $promptDir -Force | Out-Null

$promptPath = Join-Path $promptDir "web-worker.md"
if ((Test-Path -LiteralPath $promptPath) -and -not $Force) {
    [void]$skipped.Add(".ai-agent-tools/web-worker.md (already present; pass -Force to overwrite)")
}
else {
    Write-WorkerPrompt -DestPath $promptPath
    [void]$wrote.Add(".ai-agent-tools/web-worker.md")
}

Write-Host ""
Write-Host "[init-repo-agents] Wrote:"
if ($wrote.Count -eq 0) { Write-Host "  (nothing)" } else { $wrote | ForEach-Object { Write-Host "  - $_" } }
Write-Host "[init-repo-agents] Skipped:"
if ($skipped.Count -eq 0) { Write-Host "  (nothing)" } else { $skipped | ForEach-Object { Write-Host "  - $_" } }

exit 0
